### ISSUE TITLE
defu not support IE 11

### ISSUE THREAD

**Issue by joey91133** [nuxt-community/axios-module#312] opened 2019-12-18 06:32 UTC
### Version

[v5.9.0](https://github.com/axios-module/releases/tag/v5.9.0)

### Reproduction link

[https://google.com](https://google.com)

### Steps to reproduce

update this from v5.8.0.

### What is expected ?

IE 11 can not use.

### What is actually happening?

IE 11 can not use.

### Additional comments?

https://github.com/jsless/defu/issues/2

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c309">#c309</a>)</em></sub></div>

**Comment by ksbgenius** [comment] 2019-12-20 02:47
me too
but i think
consola package version

when @nuxtjs/axios version 5.8.0
consola is 2.10.1

but @nuxtjs/axios version 5.9.1
consola is 2.11.1

@nuxtjs/axios downgrade is ok.. 

check consola version please.

**Comment by jianming1999** [comment] 2019-12-22 13:34
me too

Version
v5.9.0

Steps to reproduce
update this from v5.8.0.

What is expected ?
<= Android 5.1.1 can not use.

What is actually happening?
<= Android 5.1.1 can not use.

Additional comments?
jsless/defu#2

**Comment by rupertqin** [comment] 2019-12-26 03:40
me too
I degrade to v5.6.0，that doesnot depend on defu

**Comment by rupertqin** [comment] 2019-12-26 03:50
@pi0   defu is not compatible with ie10/ie11

**Comment by manniL** [comment] 2019-12-26 22:07
cc @pi0

**Comment by kevinmarrec** [comment] 2020-01-02 14:55
Should be fixed with `defu@0.0.4` : https://github.com/jsless/defu/commit/5a6de7cc7391bbd26116ab3501c6c03276b70288

But with `yarn` it doesn't seem to be possible to get it even with lock file maintenance ...

![image](https://user-images.githubusercontent.com/25272043/71673070-074c7c80-2d78-11ea-8b8d-9b43c01851ff.png)

`0.0.4` is installable, and even if manually changing resolved version in maintenance file, it keeps installing `0.0.3` :man_shrugging: 

Better should upgrade the axios module `defu` dependency to `0.0.4` to fix the issue.

/cc @pi0

**Comment by pi0** [comment] 2020-01-02 16:29
Arrow function issue resolved and axios v5.9.1 released with updated dependency. I'm just worried about `typeof` usage. Can one please double confirm it is now working fine with IE? Otherwise we need to put defu in transpile.

**Comment by joey91133** [comment] 2020-01-02 17:14
@pi0 
test with below version and add transpile defu on nuxt.config.js it's work on IE 11.
> nuxt 2.11.0
> @nuxtjs/axios 5.9.1
> defu 0.0.4
Thanks.

**Comment by pi0** [comment] 2020-01-02 19:41
@joey91133 Would you please test without transpile? If there is an error, also would you please share it?

**Comment by joey91133** [comment] 2020-01-03 07:14
@pi0 
It's work without transpile on IE 11.

**Closed** 2020-01-04 11:23 UTC
Labels: cmty:bug-report

**Comment by LuXDAmore** [comment] 2020-01-09 13:31
@pi0 The problem still persist in my case with "@nuxtjs/axios": "^5.9.2"..

Until isn't fixed, should i transpile only defu? `transpile = [ 'defu' ]`

**Comment by jjelev** [comment] 2020-01-10 16:35
Since defu 0.0.4 it's the opposite for me. IE 11 complains from syntax error.

**Comment by edwh** [comment] 2020-01-12 16:38
I found this didn't work either transpiled or not, after upgrading axios.  I got round it for IE11 by using patch-module to patch defu.  Here's the patch in case it's useful to anyone who stumbles across this thread until it's fixed fully.

diff --git a/node_modules/defu/lib/index.js b/node_modules/defu/lib/index.js
index 5258622..202c7f4 100644
--- a/node_modules/defu/lib/index.js
+++ b/node_modules/defu/lib/index.js
@@ -13,7 +13,7 @@ function defu (_obj, _defaults) {
 
```
   const obj = Object.assign({}, _defaults)
 
-  for (const key in _obj) {
+  for (let key in _obj) {
     if (key === '__proto__' || key === 'constructor') {
       continue
     }

```

**Comment by pi0** [comment] 2020-01-13 10:00
@edwh I think you are using an outdated version of defu. Latest version(s) do not use `for`:

https://unpkg.com/defu@0.0.4/lib/index.js

I think best would be to remove lock file and create it again.
