### ISSUE TITLE
settings headers in nuxt.config.js doesn't actually add the headers you set

### ISSUE THREAD

**Issue by meatherly** [nuxt-community/axios-module#323] opened 2020-01-10 21:41 UTC
### Version

[v5.9.0](https://github.com/axios-module/releases/tag/v5.9.0)

### Reproduction link

[https://github.com/meatherly/nuxtjs-axios-bug](https://github.com/meatherly/nuxtjs-axios-bug)

### Steps to reproduce

Set the common headers in the nuxt.config.js for the axios module. Then make a request with the axios module. 

### What is expected ?

It should merge the headers you add to the config with the default like the documentation says. 

### What is actually happening?

The headers are not changing. 

### Additional comments?

I've created a example repo to recreate the bug. 
- Start up the project.
- Load the index page. 
- Inspect the request to `https://jsonplaceholder.typicode.com/posts/1` in the dev tools.

You should see that the common header set in `nuxt.config.js` is missing from the request when it shouldn't be. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c318">#c318</a>)</em></sub></div>

**Comment by MLDMoritz** [comment] 2020-01-14 14:48
Probably duplicate of #311

**Comment by pi0** [comment] 2020-04-21 19:46
Thanks for report @meatherly

**Closed** 2020-04-21 19:46 UTC
Labels: cmty:bug-report
