### ISSUE TITLE
axios undefinded in nuxt +jest unit testing

### ISSUE THREAD

**Issue by vipulphysiofirst** [nuxt-community/axios-module#416] opened 2020-09-09 08:46 UTC
I am using  nuxt + jest for uniit testing , when id testing a page it has axios call in method like this  
 IN **pay.vue**
```
async pay(){
   try{
     var respone  = this.$axios.get('API_URL_HERE);
     this.fee = response.data;
   } catch(e){
      console.log(e)
   }
 }
```

and test file **pay.spec.js**

```
import { mount } from '@vue/test-utils';
import paynow from '../pages/pay';
import   axios from "axios";
import Vue from 'vue'

jest.mock("axios", () => ({
  get: () => Promise.resolve({ data: [{ val: 1 }] })
}));
 
describe("paynow.vue", () => {
  it("mocking the axios call to get posts should work", async () => {
    var wrapper = mount(paynow);
    wrapper.vm.pay() 
  });
});
```

But i am getting this error after running it.
  **TypeError: Cannot read property 'get' of undefined**
axios is injected inplugin then why it is showing undefined

**Comment by LeonAlexanderBartz** [comment] 2020-10-22 11:03
This seems to be a duplicate of:  https://github.com/nuxt-community/axios-module/issues/105

**Closed** 2021-02-03 15:18 UTC
