### ISSUE TITLE
Axios module doesn't respect config when used in server

### ISSUE THREAD

**Issue by WangHansen** [nuxt-community/axios-module#174] opened 2018-10-30 15:13 UTC
### Version

[v5.1.0](https://github.com/axios-module/releases/tag/v5.1.0)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

The axios getting called in asyncData and middlewares do not respect the setting of https true

### What is expected ?

to follow the settings and use https

### What is actually happening?

used http

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c183">#c183</a>)</em></sub></div>

**Comment by manniL** [comment] 2018-10-30 15:35
@WangHansen Reproduction is appreciated https://template.nuxtjs.org/

**Comment by WangHansen** [comment] 2018-10-30 16:59
here: https://codesandbox.io/s/m3z9y99mrj, if you refresh the page, you will see the console log with base url and current url starting with http even tho I set https to true

**Comment by WangHansen** [comment] 2018-10-30 17:48
I did some testings and it turns out that this only happens when the page is refreshed, if page is navigated, there would not be a problem. And it seems that when the page is refreshed, axios in middlewares also doesn't follow https.

**Comment by manniL** [comment] 2018-10-30 23:55
as you already noticed, it's a duplicate of #130 :ok_hand:

**Closed by manniL** 2018-10-30 23:55 UTC
Labels: cmty:bug-report
