### ISSUE TITLE
$axios.$delete body payload is missing

### ISSUE THREAD

**Issue by Bigdragon13th** [nuxt-community/axios-module#419] opened 2020-09-18 11:27 UTC
`@nuxtjs/axios` version: 5.12.2

Issue:
When trying to call API on `delete` method, the request body is missing.

Example problematic code:
```
$axios.$delete('/store/products', {
    data: {
        [
            {
                sku: '1234',
            },
        ],
    },
}
```

More information:
`@nuxtjs/axios` 5.12.1 don't have this problem

**Comment by snsxn** [comment] 2020-09-24 15:08
+1

**Comment by drocha87** [comment] 2020-09-24 17:31
I'm experiencing the same problem, looks like the Content-Type: 'application/json' is removed from headers when sending the request. I tried to intercept the request and set the Content-Type header, but without success.

**Comment by Bigdragon13th** [comment] 2020-09-29 07:59
Looks like it's the issue from Axios@0.20.0

https://github.com/axios/axios/issues/3220

**Comment by ngajhede** [comment] 2020-09-30 06:52
There is a PR (https://github.com/axios/axios/pull/3282) ready. Question is when 0.20.1 will be released.

A solution we found for now is using `axios.request({url, data, method: 'delete'});`

**Comment by avrtau** [comment] 2020-10-07 23:15
> There is a PR ([axios/axios#3282](https://github.com/axios/axios/pull/3282)) ready. Question is when 0.20.1 will be released.
> 
> A solution we found for now is using `axios.request({url, data, method: 'delete'});`

`this.$axios.$request` also works.

**Comment by jasonsaayman** [comment] 2020-10-23 16:42
Hi,

Axios version 0.21.0 has been released 🎉 please use that and let us know if that solves your issue.

Thanks

**Comment by suruaku** [comment] 2020-10-28 15:30
> Axios version 0.21.0 has been released tada please use that and let us know if that solves your issue.

The issue is [solved](https://github.com/axios/axios/pull/3282) in 0.21.0 

I made merge request with pkg update #436

**Comment by Bigdragon13th** [comment] 2020-11-04 08:03
@jasonsaayman I've tested Axios 0.21.0 and it fixed the issue, thank you.
But install @nuxtjs/axios 5.12.2 without Axios still give me Axios 0.20.0, so maybe we need to wait for @suruaku 's PR before closing this issue.

**Comment by suruaku** [comment] 2020-11-04 13:04
> But install @nuxtjs/axios 5.12.2 without Axios still give me Axios 0.20.0, so maybe we need to wait for @suruaku 's PR before closing this issue.

It is because how semver works. 
See [this post](https://michaelsoolee.com/npm-pre-1-caret-rules/ ) or straight from [documentation](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004)

**Comment by Bigdragon13th** [comment] 2020-11-06 13:41
@suruaku Yeah, I get that

**Comment by danielalvarenga** [comment] 2020-11-13 19:50
> > But install @nuxtjs/axios 5.12.2 without Axios still give me Axios 0.20.0, so maybe we need to wait for @suruaku 's PR before closing this issue.
> 
> It is because how semver works.
> See [this post](https://michaelsoolee.com/npm-pre-1-caret-rules/) or straight from [documentation](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004)

Wainting for that! :raised_hands:

**Comment by pi0** [comment] 2020-11-30 14:49
Merged by #410 and updated with v5.12.3. Sorry for delay.

**Closed by pi0** 2020-11-30 14:49 UTC
